<?php include('views/templates/header_template.phtml') ?>

<body>

    <div class="container text-center bg-light">

        <table id="cart" class="table table-hover table-condensed">
            <?php if (!empty($data['cart']) & $_SESSION['usuario'] != "invitado") { ?>

                <thead>
                    <tr>
                        <th style="width:50%">Product</th>
                        <th style="width:10%">Price</th>
                        <th style="width:8%">Quantity</th>
                        <th style="width:10%"></th>
                    </tr>
                </thead>
                <tbody>





                    <?php
                    foreach ($data['cart'] as $item) {
                        ?>

                        <tr>
                            <td data-th="Product">
                                <div class="row">
                                    <div class="col-sm-6 hidden-xs"><img src="<?php echo $item['URL'] ?>"  style="width: 30%" class="img-responsive"/></div>
                                    <div class="col-sm-6">
                                        <h4 class="nomargin"><?php echo $item['NAME'] ?></h4>
                                    </div>
                                </div>
                            </td>
                            <td data-th="Price"> <?php
                                if (!empty($item['FINALPRICE'])) {
                                    echo $item['FINALPRICE'] . "€";
                                } else {
                                    echo $item['PRICE'] . "€";
                                }
                                ?>
                            </td>
                            <td data-th="Quantity">
                                <?php echo $item['nUnits'] ?>
                            </td>

                            <?php if ($item['db'] == "yes") { ?> 
                                <td class="actions" data-th="">

                                    <a href="?controller=cart&action=deleteFromDB_final&id=<?php echo $item['ID'] ?>"><button class="btn btn-danger"><i class="fas fa-times"></i></button></a></span>
                                </td>

                            <?php } ?>

                        </tr>

                    <?php }
                    ?>

                </tbody>
                <tfoot>
                    <tr>
                        <td><a href="#" class="btn btn-warning"><i class="fa fa-angle-left"></i>Volver</a></td>
                        <td colspan="2" class="hidden-xs"></td>
                        <td><a href="?controller=cart&action=finalbuy" class="btn btn-success btn-block">Finalizar compra <i class="fa fa-angle-right"></i></a></td>
                    </tr>
                </tfoot>
            <?php } else { ?>

                <h4 class="nomargin">No tienes productos en la cesta :(</h4>

            <?php } ?>

        </table>


    </div>
    <!-- cierro div container -->

</body>

</html>
