<?php include('views/templates/header_template.phtml') ?>

<body>

    <div class="container text-center bg-light minWidth mt-5">

      <h3 class="mb-3">Progreso de compra</h3>

      <div class="progress mb-5 ml-4 mr-4">
          <div class="progress-bar width75" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
      </div>

            <?php if (!empty($data['cart']) & $_SESSION['usuario'] != "invitado") { ?>

                <div class="row">
                    <div class="col-2 col-md-2">
                    </div>
                    <div class=" col-3 col-md-3">
                        <h4>Producto</h4>
                    </div>
                    <div class="col-3 col-md-2">
                        <h4>Cantidad</h4>
                    </div>
                    <div class="col-2 col-md-3">
                        <h4>Subtotal</h4>
                    </div>
                    <div class="col-1 col-md-1">
                    </div>
                </div>
                <hr>



                <?php
                foreach ($data['cart'] as $item) {
                    ?>

                    <div class="row bg-less-light align-items-center">
                        <div class="col-2 col-md-2">

                            <img src="<?php echo $item['URL'] ?>"  class="img-responsive width100"/>

                        </div>
                        <div class="col-3 col-md-3">

                            <h5 class="nomargin"><?php echo $item['NAME'] ?></h5>

                        </div>

                        <div class="col-3 col-md-2">

                            <div class="input-group">

                                <a href="?controller=cart&action=remove_1_FromCart&id=<?php echo $item['ID'] ?>">

                                    <button type="button" class="btn btn-default btn-number" <?php
                                    if ($item['nUnits'] == 1) {
                                        echo "disabled";
                                    }
                                    ?> data-type="minus">
                                        <span class="glyphicon glyphicon-minus">-</span>
                                    </button>
                                </a>

                                <input type="text" class="form-control input-number bg-white text-center" disabled  value="<?php echo $item['nUnits'] ?>" min="1" max="<?php echo $item['STOCK'] ?>">

                                <a href="?controller=cart&action=add_1_ToCart&id=<?php echo $item['ID'] ?>">

                                    <button type="button"  class="btn btn-default btn-number" data-type="plus" data-field="quant[1]">
                                        <span class="glyphicon glyphicon-plus">+</span>
                                    </button>
                                </a>

                            </div>
                        </div>

                        <div class="col-2 col-md-3">
                            <h5><?php echo $item['nUnits'] * $item['PRICE']; ?> €</h5>
                        </div>

                        <div class="col-1 col-xs-1">
                            <?php if ($item['db'] == "yes") { ?>

                                <a href="?controller=cart&action=deleteFromDB_final&id=<?php echo $item['ID'] ?>"><button class="btn btn-danger"><i class="fas fa-times"></i></button></a></span>

                            <?php } ?>

                        </div>

                    </div>

                    <hr>

                <?php }
                ?>

                <div class="row">
                  <div class="col-8">

                  </div>
                    <div class="col-4 mb-2" >
                        <hr>
                        <h4><strong>Total <?php echo $item['TOTAL'] ?> €</strong></h4>
                        <hr>
                    </div>
                </div>
                <div class="row">

                    <div class="col-8" >
                    </div>
                    <div class="col-4 mb-2" >
                        <a href="?controller=cart&action=finalbuy" class="btn btn-success btn-block">Finalizar compra <i class="fa fa-angle-right"></i></a>
                    </div>
                </div>
            <?php } else { ?>

                <h4 class="nomargin">No tienes productos en la cesta :(</h4>

            <?php } ?>



    </div>
    <!-- cierro div container -->

</body>

</html>
