<?php include('views/templates/header_template.phtml') ?>

<body>

    <div class="container text-center bg-light mb-5 mt-3">

        <button type="submit" name="id" class="btn-danger btn btn-lg mt-4 mb-4 disabled">historial de compras</button>


        <?php if (!empty($data)) { ?>

            <div class="row">
                <div class="col-3 col-md-2">
                </div>
                <div class="col-4 col-md-6">
                    <h5>PRODUCTO</h5>
                </div>
                <div class="col-2 col-md-2">
                    <h5>PRECIO</h5>
                </div>
                <div class=" col-1 col-md-2">
                    <h5>CANTIDAD</h5>
                </div>

            </div>

            <?php $contador = 4;
            foreach ($dataOrdered as $key => $item) {

                $contador = $contador +1;

                $color = "si";
                if ($contador % 2 == 0) {
                    $color = "no";
                }
                $date = $key;
                ?>

                <fieldset>

                    <?php if ($color == "si") { ?>
                        <div class="bg-gris mt-2 mb-2">

                        <?php } ?>

                        <?php if ($color == "no") { ?>
                            <div class="mt-2 mb-2">

                            <?php } ?>

                                <legend class="bg-dark text-white" t><?php echo $date; ?></legend>

                            <?php for ($i = 0; $i <= count($item) - 1; $i++) { ?>

                                <div class="row align-items-center">
                                    <div class="col-2">

                                        <img src="<?php echo $item[$i]['URL']; ?>" class="img-responsive width100"/>

                                    </div>
                                    <div class="col-6">

                                        <h5 class="nomargin"><?php echo $item[$i]['NAME']; ?></h5>

                                    </div>

                                    <div class="col-2">

                                      <h6> <?php
                                        if (!empty($item[$i]['FINALPRICE'])) {
                                            echo $item[$i]['FINALPRICE'] . "€";
                                        } else {
                                            echo $item[$i]['PRICE'] . "€";
                                        }
                                        ?> </h6>
                                    </div>
                                    <div class="col-2">

                                        <h6><?php echo $item[$i]['nUnits'] ?><h6/>
                                    </div>

                                </div>

                                <hr>
                            <?php } ?>
                        </div>

                </fieldset>


            <?php }
            ?>

        <?php } ?>

</div>
<!-- cierro div container -->

<?php include 'views/templates/footer_template.phtml'; ?>
