<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <title></title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
        <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>

        <!-- prueba para slider -->


        <!-- cierro prueba --->


        <link rel="stylesheet" href="views/css.css">
        <script src="views/js.js"></script>
    </head>

    <?php

    if (!empty($loginFailed)) {
        echo $loginFailed['openModel'];
    }
    ?>

    <nav class="navbar navbar-expand  navbar-light bg-primary" style="border-bottom:2px solid red">

        <a href="index.php">
        <img src="views/logo1.png" class="img-logo mr-1" alt="" href="index.php">
        <span class="navbar-brand" href="#" style="color:white">Components Bear PC</span>
        </a>

        <button type="button" data-toggle="dropdown" id="categoria" onmouseover="displayMenu()" class="btn-danger">Categorias</button>

        <div class="dropdown-menu dropdown-mega bg-secondary" id="categoriesPanel">
            <div class="row container">

                <!--  recorremos el array de categorias y el de subcategorias -->
                <?php
                foreach ($data['categories'] as $key => $categoria) {
                    $idCategory = $key;
                    $nameCategory = $categoria["NAME"];
                    ?>
                    <div class="col-md-4 dropdown-mega--column">
                        <h4 style="color:black" class="dropdown-mega--menu-header" id="<?php echo $idCategory; ?>"><?php echo $nameCategory; ?></h4>
                        <div class="list-group" >

                            <?php
                            for ($i = 0; $i < count($categoria) - 1; $i++) {

                                if ($key == "NAME") {
                                    continue;
                                }

                                $idSubCategory = $categoria[$i]['ID'];
                                $nameSubCategory = $categoria[$i]['NAME'];
                                ?>
                                <a  href="?controller=products&action=view&subCategory=<?php echo $idSubCategory ?>" class="list-group-item list-group-item-action" id="<?php echo $idSubCategory ?>">
                                <?php echo $nameSubCategory ?> </a>

                                <?php } ?> </div>
                    </div>
                        <?php } ?>



            </div>
        </div>
        <!--.row-->
    </div>
    <!--.dropdown-menu .dropdown-mega-->
</div>

<form class="form-inline mx-auto" method="POST" action="index.php?controller=products&action=search">
    <input class="form-control" type="text" name="buscador" placeholder="Buscar">
</form>


<?php
if ($_SESSION['usuario'] != "invitado") {
  //  echo "<span>Hola, {$_SESSION['usuario']}  </span>";
}
?>



<!-- inicio login -->


<!-- otro log in -->

<?php if ($_SESSION['usuario'] == "invitado") { ?>

    <a href="#" class='btn btn-primary' data-toggle="modal" data-target="#loginModal">LOGIN</a>

<?php } ?>



<!-- fin login -->

<?php if ($_SESSION['usuario'] != "invitado") { ?>

  <div class="dropdown" >
    <button class="btn btn-secondary dropdown-toggle mr-2" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <i class="fa fa-user-circle  mr-1 ml-1" aria-hidden="true" ></i>  <?php echo "<span style=\"font-size:15px;\">Hola, {$_SESSION['usuario']}  </span>";?>
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

  <?php if ($_SESSION['usuario'] == "admin"){ ?>

    <a class="dropdown-item bg-light" href="?controller=products&action=add">Añadir productos</a>
    <a class="dropdown-item bg-light" href="?controller=categories&action=add">Añadir Categorias</a>
    <a class="dropdown-item bg-light" href="?controller=promotions&action=add">Crear promociones</a>
    <a class="dropdown-item bg-light" href="?controller=log&action=logout"><i class="fa fa-sign-out mr-2" aria-hidden="true"></i>Logout</a>



<?php } else { ?>


      <a class="dropdown-item disableClick" style="pointer-events: none;" href="#"><i class="fas fa-user mr-2"></i></i>Editar Perfil</a>
      <a class="dropdown-item bg-light" href="?controller=log&action=logout"><i class="fas fa-sign-out-alt mr-2"></i>Logout</a>


<?php } ?>  </div></div> <?php }?>

<!-- carrito -->

<?php if ($_SESSION['usuario'] != 'admin') { ?>

<a href="#" class="text-light" data-toggle="modal" data-target="#myModal2">
    <i class="fa fa-shopping-cart fa-2x" aria-hidden="true"></i>
    <span class="badge badge-dark">4</span>
</a>

<!-- Modal carrito compra-->

<div class="modal right fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel2">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

            <div class="modal-header ">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title float-left" id="myModalLabel2">Carrito de la compra</h4>
            </div>

            <?php if(!empty($data['cart'])){  foreach ($data['cart'] as $item) { ?>
                <li>
                    <span class="item">
                        <span class="item-left">
                            <img src="<?php echo $item['URL'] ?>" style="width:20%" alt="" />
                            <span class="item-info">
                                <span><?php echo $item['NAME'] ?></span>
                                <span><?php echo $item['nUnits'] ?></span>
                                <span>  <?php
                                  if (!empty($item['FINALPRICE'])) {
                                    echo $item['FINALPRICE']."€";
                                  } else {
                                    echo $item['PRICE']."€";
                                  }
                                  ?></span>

                            </span>
                        </span>
                        <span class="item-right">
                        <?php 
                        
                        if ($item['db'] == "yes"){ ?> 
                            
                            <a href="?controller=cart&action=deleteFromDB&id=<?php echo $item['ID']?>"><button class="btn btn-danger"><i class="fas fa-times"></i></button></a></span>
                    <?php   } else { ?>
                            <a href="?controller=cart&action=deleteFromCart&id=<?php echo $item['ID']?>"><button class="btn btn-danger"><i class="fas fa-times"></i></button></a></span>
                        <?php } ?>
                        
                            
                            
                    </span>
                </li>
            <?php }} ?>
                
                hola

        </div>
        <!-- modal-content -->
    </div>
    <!-- modal-dialog -->
</div>
<!-- modal -->

<?php } ?>

<!-- The Modal LOG IN-->
  <div class="modal fade" id="loginModal">
    <div class="modal-dialog modal-lg ">
      <div class="modal-content">

        <!-- Modal body -->
        <div class="modal-body">

          <div class="container nav-justified col-10">
            <br>
            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist">
              <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#home">Log In</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#menu1">Registro</a>
              </li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">
              <div id="home" class="container tab-pane active"><br>
                <form  action="index.php?controller=log&action=login" method="post">
                  <div class="form-group">
                    <label htmlFor='username'><span class='glyphicon glyphicon-user'></span></label>
                        <input type='text' name="username" class='form-control' id='username'
                               placeholder='Enter user' />
                  </div>
                  <div class="form-group">
                    <label htmlFor='password'><span class='glyphicon glyphicon-eye-open'></span></label>
                        <input type='text' name="password" class='form-control' id='password'
                               placeholder='Enter password' />
                  </div>
                  <div class="form-group">
                    <button id="signupSubmit" type="submit" class="btn btn-info btn-block">LOGIN</button>
                  </div>
                </form>

              </div>
              <div id="menu1" class="container tab-pane fade"><br>
                <form method="POST" action="?controller=log&action=register" role="form">
                  <div class="form-group">
                    <label class="control-label" for="signupName">Nombre Completo</label>
                    <input id="signupName" name="name" type="text" maxlength="50" placeholder="" class="form-control">
                  </div>

                  <div class="form-group">
                    <label class="control-label" for="signupName">Nombre de usuario</label>
                    <input id="signupName" name="username" type="text" maxlength="50" placeholder="" class="form-control">
                  </div>

                  <div class="form-group">
                    <label class="control-label" for="signupEmail">Email</label>
                    <input id="signupEmail" name="email" type="email" maxlength="50" class="form-control">
                  </div>

                  <div class="form-group">
                    <label class="control-label" for="signupName">Direccion</label>
                    <input id="signupName" name="address" type="text" maxlength="50" class="form-control">
                  </div>

                  <div class="form-group">
                    <label class="control-label" for="signupName">Código Postal</label>
                    <input id="signupName" name="postalCode" type="number" maxlength="5" placeholder="" class="form-control">
                  </div>

                  <div class="form-group">
                    <label class="control-label" for="signupPassword">Contraseña</label>
                    <input id="signupPassword" type="password" maxlength="25" class="form-control" placeholder="Mínimo 8 caracteres" length="40">
                  </div>
                  <div class="form-group">
                    <label class="control-label" for="signupPasswordagain">Confirma contraseña</label>
                    <input id="signupPasswordagain" name="password" type="password" maxlength="25" class="form-control">
                  </div>
                  <div class="form-group">
                    <button id="signupSubmit" type="submit" class="btn btn-info btn-block">Registrarse</button>
                  </div>

                </form>
              </div>
            </div>
          </div>

          <?php
           if (!empty($loginFailed)) {
           echo "<span>{$loginFailed['message']}</span>";
          }
         ?>

        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        </div>

      </div>
    </div>


</nav>
