<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <title></title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
        <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
        <script type="text/javascript" src="views/jquery.autocomplete.min.js"></script>


        <link rel="stylesheet" href="views/css.css">
        <script src="views/js.js"></script>

    </head>

    <!-- abrir el modal con el error de login  -->
    <?php
    if (!empty($loginFailed)) {
        echo $loginFailed['openModel'];
    }
    ?>
    <!-- cambia el color de fondo si es admin  -->

    <?php if ($_SESSION['usuario'] == "admin") { ?>

        <nav class="navbar navbar-expand  navbar-light bg-dark border-top-red">

        <?php } else { ?>
            <nav class="navbar navbar-expand  navbar-light bg-primary border-top-red" >

            <?php } ?>

            <a href="index.php">
                <img src="imgs/logo1.png" class="img-logo mr-1">
            </a>

            <button type="button" data-toggle="dropdown" id="categoria" class="btn-danger mr-6">Categorias</button>

            <div class="dropdown-menu dropdown-mega bg-secondary" id="categoriesPanel">
                <div class="row container">

                    <!--  recorremos el array de categorias y el de subcategorias -->
                    <?php
                    foreach ($data['categories'] as $key => $categoria) {
                        $idCategory = $key;
                        $nameCategory = $categoria["NAME"];
                        ?>
                        <div class="col-md-4 dropdown-mega--column">
                            <h4 class="dropdown-mega--menu-header text-white" id="<?php echo $idCategory; ?>"><?php echo $nameCategory; ?></h4>
                            <div class="list-group" >

                                <?php
                                for ($i = 0; $i < count($categoria) - 1; $i++) {

                                    if ($key == "NAME") {
                                        continue;
                                    }

                                    $idSubCategory = $categoria[$i]['ID'];
                                    $nameSubCategory = $categoria[$i]['NAME'];
                                    ?>
                                    <a  href="?controller=products&action=view&subCategory=<?php echo $idSubCategory ?>" class="list-group-item list-group-item-action" id="<?php echo $idSubCategory ?>">
                                        <?php echo $nameSubCategory ?> </a>

                                <?php } ?> </div>
                        </div>
                    <?php } ?>



                </div>
            </div>
            <!--.row-->

            <!--.dropdown-menu .dropdown-mega-->
            <div class="form-inline mx-auto" id="searchfield">
                <form method="POST" action="index.php?controller=products&action=search">
                    <input class="form-control" type="text" name="buscador" id="autocomplete" placeholder="Buscar">
                </form>
            </div>
            <div id="outputbox">
                <p id="outputcontent"></p>
            </div>
            <!-- otro log in -->

            <?php if ($_SESSION['usuario'] == "invitado") { ?>

                <a href="#" class='btn btn-danger mr-2' data-toggle="modal" data-target="#loginModal"><i class="fas fa-user"></i></a>

            <?php } ?>



            <!-- fin login -->

            <?php if ($_SESSION['usuario'] != "invitado") { ?>

                <div class="dropdown" >
                    <button class="btn btn-secondary dropdown-toggle mr-2" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-user-circle  mr-1 ml-1" aria-hidden="true" ></i> <span class="font-user">Hola, <?php echo $_SESSION['usuario'] ?></span>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

                        <?php if ($_SESSION['usuario'] == "admin") { ?>

                            <a class="dropdown-item bg-light" href="?controller=products&action=add">Añadir productos</a>
                            <a class="dropdown-item bg-light" href="?controller=categories&action=add">Añadir Categorias</a>
                            <a class="dropdown-item bg-light" href="?controller=promotions&action=add">Crear promociones</a>
                            <a class="dropdown-item bg-light" href="?controller=log&action=logout"><i class="fa fa-sign-out mr-2" aria-hidden="true"></i>Logout</a>



                        <?php } else { ?>


                            <a class="dropdown-item disableClick pointer-events-none" href="#"><i class="fas fa-user mr-2"></i></i>Editar Perfil</a>
                            <a class="dropdown-item bg-light" href="?controller=log&action=logout"><i class="fas fa-sign-out-alt mr-2"></i>Logout</a>

                        <?php } ?>  </div></div> <?php } ?>

            <!-- carrito -->

            <?php if ($_SESSION['usuario'] != 'admin') { ?>

                <a href="#" class="text-light" data-toggle="modal" id="hoverCart" data-target="#myModal2">
                    <i class="fa fa-shopping-cart fa-2x" aria-hidden="true"></i>
                    <span class="badge badge-dark"><?php
                        if (!empty($data['cart'])) {
                            echo count($data['cart']);
                        } else {
                            echo '0';
                        }
                        ?> </span>
                </a>

                <!-- Modal carrito compra-->

                <div class="modal right fade open-cart" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel2">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">

                            <div class="modal-header ">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <h4 class="modal-title float-left" id="myModalLabel2">Carrito de la compra</h4>
                            </div>

                            <?php if ($_SESSION['usuario'] != "invitado") { ?>
                                <div class="form-group ml-2 mr-2">
                                    <a href="?controller=cart&action=finalCart"><button id="signupSubmit" type="submit" class="btn btn-info btn-block mt-2">Ir a la cesta</button></a>
                                </div>
                            <?php } ?>
                            <?php if (!empty($data['cart'])) { ?>

                                <h5 class="text-center mb-2">Progreso de compra</h5>

                                <div class="progress mb-5 ml-2 mr-2">
                                    <div class="progress-bar width25" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>

                                <?php foreach ($data['cart'] as $item) {
                                    ?>
                                <div>
                                <li>
                                        <span class="item">
                                            <span class="item-left">
                                                <img src="<?php echo $item['URL'] ?>" class="width20" />
                                                <span class="item-info"><br>
                                                    <span class="bg-light"><?php echo $item['NAME'] ?></span><br>
                                                    <span class="bg-light">Número de Unidades: <?php echo $item['nUnits'] ?></span><br>
                                                    <span class="bg-dark text-white">  <?php
                                                        if (!empty($item['FINALPRICE'])) {
                                                            echo $item['FINALPRICE'] . "€";
                                                        } else {
                                                            echo $item['PRICE'] . "€";
                                                        }
                                                        ?></span>

                                                </span>
                                            </span>
                                        </span>
                                        <span class="item-right float-right">
                                            <?php if ($item['db'] == "yes") { ?>

                                                <a href="?controller=cart&action=deleteFromDB&id=<?php echo $item['ID'] ?>"><button class="btn btn-danger"><i class="fas fa-times"></i></button></a></span>
                                        <?php } else { ?>
                                            <a href="?controller=cart&action=deleteFromCart&id=<?php echo $item['ID'] ?>"><button class="btn btn-danger"><i class="fas fa-times"></i></button></a></span>
                                        <?php } ?>
                                        </span>

                                    </li>
                                    <div>

                                    <?php
                                }
                            }
                            ?>



                        </div>
                        <!-- modal-content -->
                    </div>
                    <!-- modal-dialog -->
                </div>
                <!-- modal -->
              </div>
            </div>

            <?php } ?>

            <!-- The Modal LOG IN-->
            <div class="modal fade" id="loginModal">
                <div class="modal-dialog modal-lg ">
                    <div class="modal-content">

                        <!-- Modal body -->
                        <div class="modal-body">

                            <div class="container nav-justified col-10">
                                <br>
                                <!-- Nav tabs -->
                                <ul class="nav nav-tabs" role="tablist">
                                    <li class="nav-item">
                                        <a class="nav-link active" data-toggle="tab" href="#home">Log In</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" data-toggle="tab" href="#menu1">Registro</a>
                                    </li>
                                </ul>

                                <!-- Tab panes -->
                                <div class="tab-content">
                                    <div id="home" class="container tab-pane active"><br>
                                        <form  action="index.php?controller=log&action=login" method="post">
                                            <div class="form-group">
                                                <label htmlFor='username'><span class='glyphicon glyphicon-user'></span></label>
                                                <input type='text' name="username" class='form-control' id='username'
                                                       placeholder='Nombre de usuario' />
                                            </div>
                                            <div class="form-group">
                                                <label htmlFor='password'><span class='glyphicon glyphicon-eye-open'></span></label>
                                                <input type='text' name="password" class='form-control' id='password'
                                                       placeholder='Contraseña' />
                                            </div>
                                            <div class="form-group">
                                                <button id="signupSubmit" type="submit" class="btn btn-primary btn-block">LOGIN</button>
                                            </div>
                                        </form>

                                    </div>
                                    <div id="menu1" class="container tab-pane fade"><br>
                                        <form>
                                            <div class="form-group" id="appendName">
                                                <label class="control-label" for="signupName">Nombre Completo</label>
                                                <input name="name" id="nameUser"  type="text" maxlength="50"  onfocusout="verify(this);" class="form-control">
                                            </div>

                                            <div class="form-group" id="appendUser">
                                                <label class="control-label" for="signupName">Nombre de usuario</label>
                                                <input  name="username" id="user"  type="text" maxlength="50"  onfocusout="verify(this);" class="form-control">
                                            </div>

                                            <div class="form-group" id="appendEmail">
                                                <label class="control-label" for="signupEmail">Email</label>
                                                <input  name="email" id="email"  type="email" maxlength="50" onfocusout="verify(this);" class="form-control">
                                            </div>

                                            <div class="form-group" id="appendStreet">
                                                <label class="control-label" for="signupName">Direccion</label>
                                                <input  name="address" id="street"  type="text" maxlength="100" onfocusout="verify(this);" class="form-control">
                                            </div>

                                            <div class="form-group" id="appendCP">
                                                <label class="control-label" for="signupName">Código Postal</label>
                                                <input  name="postalCode" type="number" id="cp"  onfocusout="verify(this);"  class="form-control ">
                                            </div>


                                            <div class="form-group" id="appendPasswd">
                                                <label class="control-label" for="signupPassword">Contraseña</label>
                                                <input  type="password" id="passwd1"  maxlength="25" class="form-control" onfocusout="verify(this);" placeholder="Mínimo 8 caracteres" length="40">
                                            </div>
                                            <div class="form-group" id="appendPasswd2">
                                                <label class="control-label" for="signupPasswordagain">Confirma contraseña</label>
                                                <input  name="password" id="passwd2"  type="password" onfocusout="verify(this);" maxlength="25" class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <button  type="submit" id="registrBut" class="btn btn-primary btn-block" onclick="verificar()">Registrarse</button>
                                            </div>

                                        </form>
                                    </div>
                                </div>
                            </div>

                            <?php
                            if (!empty($loginFailed)) {
                                echo "<span>{$loginFailed['message']}</span>";
                            }

                            if (!empty($failed)) {
                                echo "<span>{$failed['message']}</span>";
                            }
                            ?>

                            <!-- Modal footer -->
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                            </div>

                        </div>
                    </div>
                  </div>
                </div>


                    </nav>
